### ISSUE TITLE
Build issue : ServerMessage could not be found

### ISSUE THREAD

**Issue by JulesThuillier** [cxz456999/NATPTransport#1]
Hi mate ! 
I was going to test this new version (congratulations by the way !!!), I had the following issue while trying to build on my Ubuntu 16 server :
![image](https://user-images.githubusercontent.com/8751523/85032290-a5c57200-b14d-11ea-954d-6ebc00a9e7ab.png)

Same problem on Windows 10 in Visual Studio.

I feel like we are just missing an import or the ServerMessage file.

Cheers !

**Comment by cxz456999** [comment]
yup... I uploaded wrong folder...
Fixed~
